version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: develop
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
